-- =================================================================
--  RookLift Initial Database Schema
-- =================================================================
--  This script creates the initial tables required for the app.
--  Run this in your Supabase SQL Editor to set up the database.
-- =================================================================

-- -----------------------------------------------------
--  Table: lichess
--  Stores daily chess rating data from Lichess.
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lichess (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    rating_morning INTEGER,
    rating_evening INTEGER,

    --  Ensure each date can only appear once
    CONSTRAINT unique_lichess_date UNIQUE (date)
);

-- Add comments for clarity
COMMENT ON TABLE public.lichess IS 'Stores daily chess rating data from Lichess.';

-- Create an index for faster lookups by date
CREATE INDEX IF NOT EXISTS idx_lichess_date ON public.lichess(date);

-- Enable Row Level Security (RLS)
-- Recommended for all tables exposed to the client
ALTER TABLE public.lichess ENABLE ROW LEVEL SECURITY;

-- Create policies to allow access
-- This policy allows all operations for authenticated users.
CREATE POLICY "Allow all operations for authenticated users"
ON public.lichess
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);